# Dependencies
markdown:         kramdown
highlighter:      rouge


# Permalinks
permalink:        pretty

# Setup
title:            
tagline:          ''
description:      ''
baseurl:          ""

theme: jekyll-theme-architect