# Dependencies
markdown:         kramdown
highlighter:      rouge


# Permalinks
permalink:        pretty

# Setup
title:            Welcome to Ksenia's homepage!
tagline:          ''
description:      'Hi all!'
baseurl:          ""

theme: jekyll-theme-architect
